events {}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    upstream backend_pool {
        server node1:8081;
        server node2:8082;
        server node3:8083;
    }
    
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://backend_pool;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
