events {}

http {
    upstream backend_pool {
        server node1:8081;
        server node2:8082;
        server node3:8083;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend_pool;
        }
    }
}
